### ISSUE TITLE
Permission problems with codesign 

### ISSUE THREAD

**Issue by hamsternik** [XVimProject/XVim#1000]
I have made all points from [INSTALL_Xcode8.md](https://github.com/hamsternik/XVim/blob/develop/INSTALL_Xcode8.md) and at the third paragraph, I got some problems.

There's a log message after ``codesign`` command
``` bash
/Applications/Xcode.app: replacing existing signature
/Applications/Xcode.app: Permission denied
```

So, as I understand, I don't change Xcode code sign to the new, created before, by installation guide? How fix that?

**Comment by iSevenDays** [comment]
Please try to run with "sudo"

**Comment by luryson** [comment]
I have encountered the same problem, and I had tried that command with sudo. But it's still not working.

**Comment by hamsternik** [comment]
agree with @luryson

**Comment by hamsternik** [comment]
So, today I could resolve this problem. I don't fully understand what was the problem, but I could install XVim plugin with XCode8 by a few steps:
1. Opened **Keychain Access** and found a new custom certificate, which had been created according to [INSTALL_Xcode8 guide](https://github.com/XVimProject/XVim/blob/master/INSTALL_Xcode8.md).
2. Removed this certificate and created the new one (actually, named it **XcodeSigner** as before).
3. After creating fired this command into console: 
```
sudo codesign -f -s XcodeSigner /Applications/Xcode.app
```
And the most interesting, I didn't get any permission problems since the first attempt!

After that, followed by the main installation guide into **README** and, finally, installed the XVim as a third-party plugin.
