### ISSUE TITLE
Xvim doest not working on XCode 8.2

### ISSUE THREAD

**Issue by VerachadW** [XVimProject/XVim#1029]
# Operation
I had follow on the steps in INSTALL.md of Xcode8. After I opened XCode, It seem like XVim is not loaded at all. Also, uninstall and reinstall XVim is not solve the problem.

# Expected behaviour
It should working properly.

# Environments
  - Xcode Version [ 8.2 ]
  - XVim branch and revision [ master ]
  - Keyboard Language [  English   ]
  - Input source language [  English  ]

# Crash log (if any)
   
     [ Paste the log here ]

**Comment by jianghaoyuan2007** [comment]
I also met this problem.

**Comment by VerachadW** [comment]
Okay, I solved the problem now. Here is what I had done.

- Update XCode to 8.2.1
- Resign XCode and install XVim
- Open Xcode and  load the bundle

Now it's working. I will close the issue.
