### ISSUE TITLE
Xcode 8.2.1 can't be Signed!

### ISSUE THREAD

**Issue by tanpengsccd** [XVimProject/XVim#1031]
# Description
Xcode 8.2.1 can't be Signed!
show
```
➜  ~ sudo codesign -f -s XcodeSigner /Applications/Xcode.app
/Applications/Xcode.app: replacing existing signature
[1]    2833 segmentation fault  sudo codesign -f -s XcodeSigner /Applications/Xcode.app
```

# Operation
Xcode update 8.2.1 from  8.2
# Expected behaviour
[Write here]

# Environments
  - Xcode Version [  8.2.1  ]

**Comment by jazzsasori** [comment]
@tanpengsccd 
I had same problem but resolved.
follows:

1. remove XCodeSigner code sign from Keychain
2. recreate XCodeSigner code sign
3. run `sudo codesign -f -s XcodeSigner /Applications/Xcode.app`

**Comment by tanpengsccd** [comment]
@jazzsasori  YES , it worked another Mac! thanks!
