### ISSUE TITLE
XCode 8.3 (develop): Installs fine, but doesn't work?

### ISSUE THREAD

**Issue by Kleptine** [XVimProject/XVim#1060]
I've installed the develop branch of XVim to my XCode 8.3.1 (newly downloaded yesterday). It built fine, installed the package, and I clicked the "load" button when XCode booted. 

However, nothing seems to have changed in XCode. Is there a setting I need to enable to get Vim functionality working..? I have an empty .xvimrc at the moment.

**Comment by ashah023** [comment]
Interesting. I did the same today and it worked fine for me, no problems. I ran `make uninstall` first though, to remove any old files. I'm not sure if that helps.

**Comment by Kleptine** [comment]
Just to be clear, I don't have to enable anything first? XCode should just
load plugins automatically? This is also my first time using XCode.

Is there any way I can verify that the plugin code is loaded / running?
Should there be print outs in a log somewhere?

The plugin also seems to be installed int he XCide plugins folder and has
the correct UUID in the properties.

I tried the uninstall, but no dice there either.

**Comment by TRHoward** [comment]
Since you're using Xcode 8, did you first follow https://github.com/XVimProject/XVim/blob/master/INSTALL_Xcode8.md ?

I just did a clean install from develop and it worked fine.

**Comment by Kleptine** [comment]
Dang! Yep, wow, sorry for taking your time. 

I saw that link on the main page, but I assumed I was already reading that install readme on the main page, rather than it being a different guide. Seems to work fine now!

Thanks
