### ISSUE TITLE
Xcode 8.3.1 Build success, but plugin non-functional

### ISSUE THREAD

**Issue by jkrmr** [XVimProject/XVim#1061]
# Description

Courtesy of @cuongv:

> I can install Xvim successfully by using develop branch, but no VIM feature in Xcode when I open projects. Xcode works like it did before install Xvim. ( Already allow xcode load Xvim from bundles).

# Operation
```
XVim develop % make
xcodebuild -configuration Release
=== BUILD TARGET XVim OF PROJECT XVim WITH CONFIGURATION Release ===

# . . .

** BUILD SUCCEEDED **

```

# Expected behaviour
XVim working in Xcode.

# Environments
  - Xcode Version [  8.3.1  ]
  - XVim branch and revision [  develop / fa5224b  ]
  - Keyboard Language [   English US  ]
  - Input source language [  English US  ]

# Crash log (if any)
   
 n / a

**Comment by JugglerShu** [comment]
Have you code re-sign Xcode? (See here if not yet. https://github.com/XVimProject/XVim/blob/master/INSTALL_Xcode8.md )

**Comment by saiday** [comment]
resign Xcode then using `develop` branch works for me.

**Comment by jkrmr** [comment]
My mistake—I completely overlooked that step. Thanks!

**Comment by kevin-corcoran** [comment]
Yes using the develop branch worked! 

first I removed it
rm -rf XVim/

added the develop branch
git clone --branch develop https://github.com/XVimProject/XVim.git
