### ISSUE TITLE
Can't make

### ISSUE THREAD

**Issue by 56phil** [XVimProject/XVim#1072]
# Description
Make failed, after creating a new signing certificate. See below:
# Operation

- Entered XVim directory
- typed make

# Expected behaviour
success 
# Environments
  - Xcode Version [ 8.3.2]
  - XVim branch and revision [     ]
  - Keyboard Language [ English    ]
  - Input source language [English    ]

# Crash log (if any)
   

** BUILD FAILED **

The following build commands failed:
	Ld build/Release/XVim.xcplugin/Contents/MacOS/XVim normal x86_64
(1 failure)
make: *** [release] Error 65

**Comment by michaelbarlow7** [comment]
Pretty sure this is a duplicate of https://github.com/XVimProject/XVim/issues/1069. There is a workaround posted there that fixes the problem.

**Comment by 56phil** [comment]
That's what I needed. Thanks!
