### ISSUE TITLE
Xcode 8.3.2 not work

### ISSUE THREAD

**Issue by lenvonsam** [XVimProject/XVim#1085]
# Description
I follow the steps util make step, and then create .xvimrc file still not work

# Operation
![image](https://user-images.githubusercontent.com/10168476/29439851-2c5a5f82-83f3-11e7-80c3-aa35ee004068.png)

![image](https://user-images.githubusercontent.com/10168476/29439831-06263b4c-83f3-11e7-9d40-9e9700a265f5.png)

# Environments
  - Xcode Version [ 8.3.2   ]
  - XVim branch and revision [  last version   ]

**Comment by XhinLiang** [comment]
checkout the develop branch and try again.

**Comment by lenvonsam** [comment]
@XhinLiang thx, the problem is resolved
