### ISSUE TITLE
Yanking overwrites whatever last used register was

### ISSUE THREAD

**Issue by mcsimenc** [XVimProject/XVim#1102]
# Description
Yanking overwrites whatever last used register was

# Operation
If I yank to register a, then yank to register b, then put register a to replace string C, then register a will have C and b will remain unchanged.

# Expected behaviour
When putting a register's contents, whatever gets replaced should go into the default register but not the specific register used. At least that's the default behavior in my version of Vim.

# Environments
  - Xcode Version [10.1+ ]
  - XVim branch and revision [XVim2 revision : 5c7aaa56e2d39ed2dd9ad42b7f14e4c91ee59218
OS Version : Version 10.14 (Build 18A391)
Xcode Version : 10.1]
  - Keyboard Language [English]
  - Input source language [English]

**Comment by hyouuu** [comment]
A great to fix bug!

**Comment by mcsimenc** [comment]
I just realized I posted this in XVim issues not XVim2. I don't know if it's an issue in XVim1. Anyways, thanks for your work. I love XVim!
