### ISSUE TITLE
Jump list is not implemented [$100]

### ISSUE THREAD

**Issue by kabuko** [XVimProject/XVim#159]
There are a whole bunch of commands around jumps that could be implemented, but some of the ones that stand out to me are:

```
''  ``			To the position before the latest jump, or where the
			last "m'" or "m`" command was given.  Not set when the
			|:keepjumps| command modifier was used.
			Also see |restore-position|.

							CTRL-O
CTRL-O			Go to [count] Older cursor position in jump list
			(not a motion command).  {not in Vi}
			{not available without the |+jumplist| feature}

<Tab>		or					CTRL-I <Tab>
CTRL-I			Go to [count] newer cursor position in jump list
			(not a motion command).
			In a |quickfix-window| it takes you to the position of
			the error under the cursor.
			{not in Vi}
			{not available without the |+jumplist| feature}

							:ju :jumps
:ju[mps]		Print the jump list (not a motion command).  {not in
			Vi} {not available without the |+jumplist| feature}

```

**Comment by jeffpearce** [comment]
I'm interested in working on this, but I can't tell whether someone's already looking at it. It looks like several people have started - is anyone still actively working on it?

**Comment by lando2319** [comment]
Jeff, see the bountysource links, as I understand it if there is no one listed under "Developer" that means its available. 
https://www.bountysource.com/issues/900222-jump-list-is-not-implemented-100

The link above is the one I am backing, but there is also another bounty for the same issue in the link below. This is also available.  

https://www.bountysource.com/issues/4486160-ctrl-o-ctrl-i-isn-t-supported-100

Looks like you have an opportunity to collect both bounties.

**Comment by pebble8888** [comment]
I'm sorry I leave my patch `CTRL-i` `CTRL-o` `jumps`.
I will send `jumplist` PR. 
Please check it satisfy your wants.

**Comment by pebble8888** [comment]
The feature has been merged to the master branch.
Please close the issue if the feature meets your needs.

**Comment by JugglerShu** [comment]
I close this. Please reopen if you still have problems.
