### ISSUE TITLE
Toggle XVim (enable/disable)

### ISSUE THREAD

**Issue by aam1r** [XVimProject/XVim#279]
Having used Vrapper for Eclipse, I really liked the feature to ' Toggle Vrapper' which let me enable/disable vim keybindings very easily. Something like that would be very handy for Xcode.

I often have people working on my IDE (while pair programming, troubleshooting) and there's no way for me to temporarily disable XVim AFAIK.

**Comment by mariancerny** [comment]
It's in the menu in Editor > XVim > Enable.

**Comment by Khalian** [comment]
@mariancerny There is no XVim under Editor post installation.

**Comment by the-yuyut** [comment]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/42088295/55790495-09d2bc00-5aef-11e9-8284-2eabd35f8ac8.png">

It's in the menu in Edit > XVim > Enable, (in Xcode 10.2, XVim2)
