### ISSUE TITLE
Find and replace ignores 'c' (confirm) option [$50]

### ISSUE THREAD

**Issue by khatchad** [XVimProject/XVim#325]
The following command ignores the 'c' (confirm) option and instead just replaces any found text.

:%s/a/b/gc

**Comment by jeffpearce** [comment]
Sent a PR for an implementation: https://github.com/XVimProject/XVim/pull/699.

**Comment by jeffpearce** [comment]
PR merged into development branch - can this issue be closed now?

**Comment by JugglerShu** [comment]
Keep it until it is merged into master. Thanks.

**Comment by jeffpearce** [comment]
Sounds good, thanks.

**Comment by jeffpearce** [comment]
I think this is in master now

**Comment by lando2319** [comment]
This issue should be closed. It's on master now.
