### ISSUE TITLE
Crash in XCode 5 GM if build phases contains a run script phase.

### ISSUE THREAD

**Issue by seepel** [XVimProject/XVim#462]
If you have a run script build phase and try to navigate away from the build phases pane XVim will crash. This is especially brutal because XCode will remember that you were on the build phases pane and it becomes very difficult to get back to a working state.

My local copy of XVim is kind of a mess right now, not sure when I could find time to clean it up and take a look at this.

Process:         Xcode [15130]
Path:            /Applications/Xcode.app/Contents/MacOS/Xcode
Identifier:      com.apple.dt.Xcode
Version:         5.0 (3332.22)
Build Info:      IDEApplication-3332022000000000~2
Code Type:       X86-64 (Native)
Parent Process:  launchd [154]
User ID:         501

Date/Time:       2013-09-18 13:22:56.140 -0700
OS Version:      Mac OS X 10.8.4 (12E55)
Report Version:  10

Interval Since Last Report:          4479952 sec
Crashes Since Last Report:           404
Per-App Interval Since Last Report:  79274 sec
Per-App Crashes Since Last Report:   22
Anonymous UUID:                      055E2C61-9208-BBBD-E27D-8A84F1CCACD7

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
ProductBuildVersion: 5A1412
UNCAUGHT EXCEPTION (NSRangeException): Cannot remove an observer <DVTScriptSourceTextView 0x7fb745fbb900> for the key path "hlsearch" from <XVimOptions 0x7fb73f305370> because it is not registered as an observer.
UserInfo: (null)
Hints: None
Backtrace:
  0  0x00007fff8de5eaee __exceptionPreprocess (in CoreFoundation)
  1  0x000000010f2b6c23 DVTFailureHintExceptionPreprocessor (in DVTFoundation)
  2  0x00007fff8f9183f0 objc_exception_throw (in libobjc.A.dylib)
  3  0x00007fff8de5e8dc +[NSException raise:format:](in CoreFoundation)
  4  0x00007fff9174ce81 -[NSObject(NSKeyValueObserverRegistration) _removeObserver:forProperty:](in Foundation)
  5  0x00007fff9174cb48 -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:](in Foundation)
  6  0x00000001195e8760 -[DVTSourceTextViewHook dealloc](in XVim)
  7  0x00007fff9387f3b7 -[NSTextView release](in AppKit)
  8  0x00007fff902646a3 _Block_release (in libsystem_blocks.dylib)
  9  0x00007fff902646a3 _Block_release (in libsystem_blocks.dylib)
 10  0x00007fff93538139 _dispatch_source_invoke (in libdispatch.dylib)
 11  0x00007fff93537305 _dispatch_queue_invoke (in libdispatch.dylib)
 12  0x00007fff9353b091 _dispatch_main_queue_callback_4CF (in libdispatch.dylib)
 13  0x00007fff8de00b4c __CFRunLoopRun (in CoreFoundation)
 14  0x00007fff8de000e2 CFRunLoopRunSpecific (in CoreFoundation)
 15  0x00007fff91278eb4 RunCurrentEventLoopInMode (in HIToolbox)
 16  0x00007fff91278c52 ReceiveNextEventCommon (in HIToolbox)
 17  0x00007fff91278ae3 BlockUntilNextEventMatchingListInMode (in HIToolbox)
 18  0x00007fff937d6533 _DPSNextEvent (in AppKit)
 19  0x00007fff937d5df2 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:](in AppKit)
 20  0x00007fff937cd1a3 -[NSApplication run](in AppKit)
 21  0x00007fff93771bd6 NSApplicationMain (in AppKit)
 22  0x00007fff9295d7e1 start (in libdyld.dylib)
 23  0x0000000000000002

**Comment by nizarahmed** [comment]
This is happening with me again on XCode 7.3.1
