### ISSUE TITLE
Lost focus when using next/previous counterpart [$15]

### ISSUE THREAD

**Issue by minhhien177** [XVimProject/XVim#537]
Every time I use next counterpart (:nc) or previous counterpart shortcut (:pc), I lose focus on the current window and I have to use my mouse to get back to it (Xcode5 + Mac 10.9). It worked fine before but not anymore after I update XVim. ctrl+shift+up or ctrl+shift+down still focus on the current window.

Hope there will be a way to fix it, thank you.

**Comment by caoer** [comment]
:+1: fb3a922 fixed the issue
