### ISSUE TITLE
ctrl+o, ctrl+i isn't supported [$100]

### ISSUE THREAD

**Issue by hurshagrawal** [XVimProject/XVim#626]
XVim doesn't seem to support ctrl+o, ctrl+i (http://vim.wikia.com/wiki/Jumping_to_previously_visited_locations). It would be *amazing* if it could support the jump list and navigating it.

**Comment by pebble8888** [comment]
jumplist feature is merged to the master branch.
Please check it.

**Comment by hurshagrawal** [comment]
Awesome! Hmm, can't figure out how to award you the bounty. Do you have to mark it as done on bountysource somehow?

**Comment by pebble8888** [comment]
First close the issue if the feature satisfied you.
It makes me claim the bounty.

**Comment by hurshagrawal** [comment]
Thank you so much for doing this! Works great :)
