### ISSUE TITLE
Don't run in xcode Version 6.0.1

### ISSUE THREAD

**Issue by liberathor** [XVimProject/XVim#628]
To tun project in xcode 6.0.1 in os x 10.9.4 don't start and show this log:

2014-09-22 09:55:46.168 Xcode[17235:303] [MT] DVTAssertions: UNCAUGHT EXCEPTION (NSInternalInconsistencyException): Extension Xcode.IDEKit.CmdHandler.ShowViewFrames class 'DBGMenuController' not found for required key 'handlerClass'
UserInfo: {
    DVTExtensionClassNameErrorKey = DBGMenuController;
    DVTExtensionIdentifierErrorKey = "Xcode.IDEKit.CmdHandler.ShowViewFrames";
    DVTPlugInExecutablePathErrorKey = "/Applications/Xcode.app/Contents/PlugIns/DebuggerUI.ideplugin";
    DVTPlugInIdentifierErrorKey = "com.apple.dt.dbg.DebuggerUI";
}
Hints: None
2014-09-22 09:55:46.667 Xcode[17235:303] [MT] DVTAssertions: 
Backtrace:
  0  0x00007fff89c00244 __exceptionPreprocess (in CoreFoundation)
  1  0x00000001001e6184 DVTFailureHintExceptionPreprocessor (in DVTFoundation)
  2  0x00007fff8f647e75 objc_exception_throw (in libobjc.A.dylib)
  3  0x000000010004ebd7 -[DVTExtension _adjustClassAttribute:forKey:inParameterData:] (in DVTFoundation)
  4  0x000000010004e633 -[DVTExtension _adjustClassReferencesInParameterData:usingSchema:] (in DVTFoundation)
  5  0x00000001000d210c -[DVTExtension _fireExtensionFault:] (in DVTFoundation)
  6  0x00000001000d1a75 __63-[DVTExtension _valueForKey:inParameterData:usingSchema:error:]_block_invoke (in DVTFoundation)
  7  0x0000000101fa8925 _dispatch_client_callout (in libdispatch.dylib)
  8  0x0000000101fa98df _dispatch_barrier_sync_f_invoke (in libdispatch.dylib)
  9  0x000000010021cdfd DVTDispatchBarrierSync (in DVTFoundation)
 10  0x000000010001fbc4 -[DVTDispatchLock performLockedBlock:] (in DVTFoundation)
 11  0x00000001000d1851 -[DVTExtension _valueForKey:inParameterData:usingSchema:error:] (in DVTFoundation)
 12  0x00000001000d1c44 -[DVTExtension valueForKey:error:] (in DVTFoundation)
 13  0x00000001014173de __55+[IDECommandManager cacheCommandDefinitionsAndHandlers]_block_invoke (in IDEKit)
 14  0x0000000101fa8925 _dispatch_client_callout (in libdispatch.dylib)
 15  0x0000000101fa891b dispatch_once_f (in libdispatch.dylib)
 16  0x00000001011d0a60 +[IDECommandManager cacheCommandDefinitionsAndHandlers] (in IDEKit)
 17  0x00000001011d0054 -[IDEApplicationController applicationWillFinishLaunching:] (in IDEKit)
 18  0x00007fff89bcee0c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ (in CoreFoundation)
 19  0x00007fff89ac282d _CFXNotificationPost (in CoreFoundation)
 20  0x00007fff8c1397ba -[NSNotificationCenter postNotificationName:object:userInfo:] (in Foundation)
 21  0x00000001001c6e6e -[NSNotificationCenter(DVTNSNotificationCenterAdditions) _dvt_postNotificationName:object:userInfo:] (in DVTFoundation)
 22  0x00007fff8881ecde -[NSApplication finishLaunching] (in AppKit)
 23  0x000000010074a665 -[DVTApplication finishLaunching] (in DVTKit)
 24  0x00007fff8881e7f3 -[NSApplication run] (in AppKit)
 25  0x00007fff88809783 NSApplicationMain (in AppKit)
 26  0x00007fff8deac5fd start (in libdyld.dylib)

**Comment by Keithbsmiley** [comment]
@JugglerShu this fixed this crash for me. It looks like this change should be checked in?

**Comment by Keithbsmiley** [comment]
For others reading this, this has been fixed on the current develop branch.

**Comment by liberathor** [comment]
Thanks!! for fix this problem.
