### ISSUE TITLE
XVim not reading ~/.xvimrc

### ISSUE THREAD

**Issue by mantislin** [XVimProject/XVim#645]
I'm using xCode 6.1 and I added something in ~/.xvimrc but got no effects. I've searched in issues but seemed not found any issue like this.
My ~/.xvimrc just like this:

" XVim UI
set incsearch " BUT do highlight as you type you search phrase
set linespace=0 " don't insert any extra pixel lines betweens rows
set listchars=tab:>-,trail:- " show tabs and trailing
set hlsearch " do not highlight searched for phrases
set nostartofline " leave my cursor where it was
set novisualbell " don't blink
set report=0 " tell us when anything is changed via :...
set scrolloff=10 " Keep 10 lines (top/bottom) for scope
set shortmess=aOstT " shortens messages to avoid 'press a key' prompt
set showcmd " show the command being typed
set showmatch " show matching brackets
set sidescrolloff=10 " Keep 5 lines at the size
set statusline=%F%m%r%h%w[%L][%{&ff}]%y[%p%%][%04l,%04v]

" GUI Settings
set guioptions=ce

" Mappings
noremap <buffer> <silent> k gk
noremap <buffer> <silent> j gj
noremap <buffer> <silent> 0 g0
noremap <buffer> <silent> $ g$
noremap <buffer> <silent> ^ g^

**Comment by ooopscc** [comment]
@JugglerShu @mantislin Thanks, I just want a case insensitive search, now it worked!
