### ISSUE TITLE
Replace (capital R) doesn't work

### ISSUE THREAD

**Issue by slooker** [XVimProject/XVim#668]
Replace, capital R when not in edit mode, should turn on overwrite and allow you to overwrite text.
##

**Comment by Keithbsmiley** [comment]
There is currently an open PR for this https://github.com/XVimProject/XVim/pull/667

**Comment by donokuda** [comment]
@slooker This was merged in https://github.com/XVimProject/XVim/pull/690 and is now in master. Looks like this issue can be closed.
