### ISSUE TITLE
Shift-O on last line doesn't appear to work

### ISSUE THREAD

**Issue by es2mac** [XVimProject/XVim#675]
Shift-O, creating a new line above the current line and enter insert mode, doesn't seem to have any effect when the cursor is on the last line of a file.

**Comment by Meganezaru** [comment]
I got same thing.
It looks it doesn't work when the last line is just blank line.

**Comment by Keithbsmiley** [comment]
I have submitted a PR to the develop branch to fix this issue. Please check out the mentioned branch and confirm that it is fixed!
