### ISSUE TITLE
Xcode 6.2 Broken

### ISSUE THREAD

**Issue by brandonroth** [XVimProject/XVim#707]
Xvim isn't available when upgrading to Xcode 6.2.  Building a new version doesn't fix the issue.  If I switch to Xcode 6.1.1 or 6.3 beta 2 then get it back.

**Comment by deomitrus** [comment]
+1 on this. After updating Xcode to 6.2 XVim is broken. I have tried rebuilding as well.

**Comment by ccwasden** [comment]
See the change made in the referenced commit above, make that change in the XVim project, then manually build

**Comment by deomitrus** [comment]
Yeap, just saw that commit. I tried it out and it works now. Thanks.
