### ISSUE TITLE
:nohl or :nohlsearch is broken [$15]

### ISSUE THREAD

**Issue by supermarin** [XVimProject/XVim#719]
After searching, you clear the highlights using `:nohlsearch`.
It works immediately, but as soon as you start editing it highlights everything back again.

__Expected__:
Words aren't highlighted anymore until you perform another search

__Actual__:
Words are getting highlighted with the previous search

**Comment by mkc188** [comment]
+1 for the same issue

**Comment by lando2319** [comment]
So it looks like using "i", "I", "a", or "A" works as expected, but "o" and "O" are causing the highlighting to reappear.
