### ISSUE TITLE
XVim not reading ~/.xvimrc in XCode 6.2

### ISSUE THREAD

**Issue by andrewsyntertainment** [XVimProject/XVim#725]
Here is my .xvimrc file. It's name xvimrc.xvimrc and is located in the home directory.

imap jk Esc 
(with carrots around the Esc)

It is not read by XVim, though running ':imap jk Esc' works as expected within XCode. This suggests its a different issue than #645

**Comment by lando2319** [comment]
the file should be named just .xvimrc. I have the same command in my xvimrc and it is working for me.

**Comment by andrewsyntertainment** [comment]
I get this error when trying to rename it to .xvimrc

"You can’t use a name that begins with a dot “.”, because these names are reserved for the system. Please choose another name."

**Comment by andrewsyntertainment** [comment]
Ah figured it out, you need to do it with terminal. In my case:

cd ~
mv xvimrc.xvimrc .xvimrc

Successfully renamed it and is now working! Thanks Lando! Closing issue.

**Comment by lando2319** [comment]
Great to hear.

**Comment by mayqiyue** [comment]
Anyone knows why 'set cursorcolumn' not  work in .xvimrc?
