### ISSUE TITLE
XVim doesn't work in Xcode 6.3 with Yosemite 10.10.3

### ISSUE THREAD

**Issue by Douglas-Su** [XVimProject/XVim#729]
I updated Yosemite 10.10.3 and Xcode 6.3. After I recompiled the XVim, however, it doesn't work any longer. How could I fix this problem?

**Comment by fuzhuo** [comment]
Seems need add UUID to support Xcode6.3..

I tried below...
Edit file: XVim/Info.plist

<array>
   ...............
  <string>FEC992CC-CA4A-4CFD-8881-77300FCB848A</string>
+  <string>9F75337B-21B4-4ADC-B558-F9CADF7073A7</string>

**Comment by rianrainey** [comment]
@Douglas-Su did you re-pull the master branch and re-make? That made it work for me.

**Comment by Douglas-Su** [comment]
@rianrainey It works, Thanks a lot
