### ISSUE TITLE
crash for gg and k in develop branch

### ISSUE THREAD

**Issue by pebble8888** [XVimProject/XVim#739]
Process:               Xcode [6247]
Path:                  /Applications/Xcode.app/Contents/MacOS/Xcode
Identifier:            com.apple.dt.Xcode
Version:               6.3 (7569)
Build Info:            IDEFrameworks-7569000000000000~2
App Item ID:           497799835
App External ID:       812135760
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Xcode [6247]
User ID:               501

Date/Time:             2015-04-21 12:57:05.925 +0900
OS Version:            Mac OS X 10.10.3 (14D136)
Report Version:        11
Anonymous UUID:        94417408-EF84-C65F-1911-5B98F237B52D

Sleep/Wake UUID:       2D69D3B3-92C2-45F1-ABF5-43D57DA0A68F

Time Awake Since Boot: 7400 seconds
Time Since Wake:       760 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
ProductBuildVersion: 6D570
UNCAUGHT EXCEPTION (NSInternalInconsistencyException): Line numbers start at 1
UserInfo: (null)
Hints: None
Backtrace:
  0  0x00007fff8ce7c024 __exceptionPreprocess (in CoreFoundation)
  1  0x000000010e641184 DVTFailureHintExceptionPreprocessor (in DVTFoundation)
  2  0x00007fff841d176e objc_exception_throw (in libobjc.A.dylib)
  3  0x00007fff8ce7be1a +[NSException raise:format:arguments:] (in CoreFoundation)
  4  0x00007fff8b2368cb -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] (in Foundation)
  5  0x000000011e11f093 -[DVTTextStorage(XVimTextStoring) xvim_indexRangeForLineNumber:newLineLength:] at /develop/XVim/XVim/DVTTextStorage+XVimTextStoring.m:35 (in XVim)
  6  0x000000011e124b1d -[NSTextStorage(VimOperation) xvim_indexOfLineNumber:] at /develop/XVim/XVim/NSTextStorage+VimOperation.m:127 (in XVim)
  7  0x000000011e126184 -[NSTextStorage(VimOperation) xvim_indexOfLineNumber:column:] at /develop/XVim/XVim/NSTextStorage+VimOperation.m:203 (in XVim)
  8  0x000000011e12cee3 -[NSTextStorage(VimOperation) prevLine:column:count:option:] at /develop/XVim/XVim/NSTextStorage+VimOperation.m:609 (in XVim)
  9  0x000000011e146979 -[NSTextView(VimOperationPrivate) xvim_getMotionRange:Motion:] at /develop/XVim/XVim/NSTextView+VimOperation.m:2176 (in XVim)
 10  0x000000011e1378ef -[NSTextView(VimOperation) xvim_move:] at /develop/XVim/XVim/NSTextView+VimOperation.m:616 (in XVim)
 11  0x000000011e09c5b7 -[XVimNormalEvaluator motionFixed:] at /develop/XVim/XVim/XVimNormalEvaluator.m:539 (in XVim)
 12  0x000000011e0a597b -[XVimMotionEvaluator _motionFixed:] at /develop/XVim/XVim/XVimMotionEvaluator.m:90 (in XVim)
 13  0x000000011e0a68e8 -[XVimMotionEvaluator k] at /develop/XVim/XVim/XVimMotionEvaluator.m:227 (in XVim)
 14  0x000000011e096087 -[XVimEvaluator eval:] at /develop/XVim/XVim/XVimEvaluator.m:80 (in XVim)
 15  0x000000011e0bb1b1 -[XVimNumericEvaluator eval:] at /develop/XVim/XVim/XVimNumericEvaluator.m:15 (in XVim)
 16  0x000000011e0e0c9f -[XVimWindow handleKeyStroke:onStack:] at /develop/XVim/XVim/XVimWindow.m:236 (in XVim)
 17  0x000000011e0e01e5 -[XVimWindow handleOneXVimString:] at /develop/XVim/XVim/XVimWindow.m:191 (in XVim)
 18  0x000000011e0e0671 -[XVimWindow handleXVimString:] at /develop/XVim/XVim/XVimWindow.m:217 (in XVim)
 19  0x000000011e0dfe93 -[XVimWindow handleKeyEvent:] at /develop/XVim/XVim/XVimWindow.m:155 (in XVim)
 20  0x000000011e0b84d0 -[DVTSourceTextView(XVim) xvim_keyDown:] at /develop/XVim/XVim/DVTSourceTextView+XVim.m:102 (in XVim)
 21  0x00007fff879b411b -[NSWindow _reallySendEvent:isDelayedEvent:] (in AppKit)
 22  0x00007fff87345d76 -[NSWindow sendEvent:] (in AppKit)
 23  0x000000010f90c118 -[IDEWorkspaceWindow sendEvent:] (in IDEKit)
 24  0x00007fff873429b1 -[NSApplication sendEvent:] (in AppKit)
 25  0x000000010f6b6494 -[IDEApplication sendEvent:] (in IDEKit)
 26  0x00007fff8726bc68 -[NSApplication run] (in AppKit)
 27  0x00007fff871e8354 NSApplicationMain (in AppKit)
 28  0x00007fff9333e5c9 start (in libdyld.dylib)
 
abort() called

Application Specific Signatures:
NSInternalInconsistencyException

**Comment by JugglerShu** [comment]
Yea, I have encountered the same issue. This is one of the sign that current develop branch is messed up at some point.

**Comment by pebble8888** [comment]
I will fix the bug and send pull request after eating dogfood for a while.
I have used develop branch at all times.
I don't think it is unstable all that much.

Cursor position after substitution in Xvim doesn't equal to origin vim.
So I will fix test case.

**Comment by JugglerShu** [comment]
Should I merge your fix for this?

**Comment by pebble8888** [comment]
Thank you for the merge into develop branch.
No crash so I close the issue.

**Comment by JugglerShu** [comment]
Ah, I didn't noticed that I have already merged your fix. Anyway it's fine.
