### ISSUE TITLE
Not working on Xcode 6.3.1

### ISSUE THREAD

**Issue by a9austin** [XVimProject/XVim#740]
Currently not working on Xcode Version 6.3.1 (6D1002)

**Comment by hyperspacemark** [comment]
Xcode 6.3.1 appears to have the same compatibility UUID as Xcode 6.3 (`9F75337B-21B4-4ADC-B558-F9CADF7073A7`). Did you happen to upgrade to 6.3.1 from a pre-6.3 version by chance? If so, you should just be able to pull the latest Xvim, run `make` and restart Xcode.

**Comment by ajh17** [comment]
Xvim is working fine for me with Xcode 6.3.1, make sure you're running the latest version of Xvim, 6.3 compatibility was just recently added to the master branch

**Comment by a9austin** [comment]
Sweet let me try that, thanks.
