### ISSUE TITLE
Using gg in visual mode 

### ISSUE THREAD

**Issue by squarefrog** [XVimProject/XVim#742]
The following command should select from the current line to the top of the file:

    Vgg

However, it strips the selection.

Conversely,

    VG

works as expected. I've added some test cases in https://github.com/squarefrog/XVim/commit/ba958ff3fbf766c29ad46ed126a5b6cd0fffe451 but I'm afraid I don't know how to implement the functionality.

**Comment by J-Fields** [comment]
Hi squarefrog.  I took a look at this and got it working for the most part.  There is an issue still (see https://github.com/J-Fields/XVim/commit/58d56066938c5f38bee436eb7cd03e49a94e987a) but please feel free to take a look at it and see if you can help me out with it.

**Comment by squarefrog** [comment]
I took a look, and it does fix one of the failing tests which is great. There are two failures remaining: 

- `vggU` - this mostly works, but using `gg` doesn't position the cursor at line 1 column 1.
- ``vGU` - again, this is almost there, but it should select *up to* the first non-whitespace column on the last line.

Onto your jump issue - I'm afraid I have no idea why that is happening. What is interesting, is if you do `v9Gj` the command works as expected. When prefixed by a number, `G` and `gg` should be exactly the same. 

It is only when there is no numerical prefix that `G` (last line)  and `gg` (first line) differ.

**Comment by squarefrog** [comment]
Digging around - it seems like the behaviour should be as follows:

> When using `g` or `G`, after moving to the line specified, or the default line, the cursor should then move to the first non-blank character on the current line.

This behaviour is matched in Vim. It is only the standard motion (`j`, `k` etc) that preserves the current column.

**Comment by JugglerShu** [comment]
@squarefrog 
I'm fixign #865. It seems jumping into line without characters by command like `1G` doesn't work now because of your commit about gg G behaviour improvement.

The code that cause this problem is this.

                // TODO: Preserve column option can be included in motion object
                if (self.selectionMode == XVIM_VISUAL_BLOCK && self.selectionToEOL) {
                    r.end = [self.textStorage xvim_endOfLine:r.end];
                } else if (XVim.instance.options.startofline) {
                    // only jump to nonblank line for last line or line number
                    if (motion.motion == MOTION_LASTLINE || motion.motion == MOTION_LINENUMBER) {
                        r.end = [self.textStorage xvim_firstNonblankInLineAtIndex:r.end allowEOL:NO];
                    }
                }

The problem is xvim_firstNonblankInLineAtIndex could return NSNotFound whne you specify `NO` to `allowEOL`. My question is if you remember the reason you specified `NO` here instead of `YES`.

It seems this change will fix the problem in #865.

**Comment by squarefrog** [comment]
@JugglerShu As far as I remember, theres no specific reason why I chose that. As long as the tests still pass its all good :+1:

**Comment by JugglerShu** [comment]
OK. Thanks
