### ISSUE TITLE
Not work for Xcode 6.3.2

### ISSUE THREAD

**Issue by zld** [XVimProject/XVim#757]

**Comment by Matt-hew** [comment]
For me I find the XVim menu item is gone and I can't disable XVim temporarily.

**Comment by lando2319** [comment]
disable? I just upgraded to 6.3.2 and XVim is not working at all.

**Comment by lando2319** [comment]
My mistake I needed to pull. XVim is working, and as mentioned the XVim menu option is gone.

I know there had been talk of moving the "XVim" menu tab, if I may suggest a solution, what about placing it under "editor", but with the option of "XVim", then have a submenu with the option to disable. 

Big Fan of XVim!

**Comment by gzjayvan** [comment]
after upgraded to 6.3.2 Xvim not working.

**Comment by JugglerShu** [comment]
Please update your XVim. (Get the latest master or develop branch).
Regarding to the XVim menu, I think it is because of the change of Xcode internal initialization behavior.
I'll see what is happening but it doesn't make much problem if you are just using XVim.

**Comment by mimaun** [comment]
I got same problem, so I
![2015-05-21 11 23 53](https://cloud.githubusercontent.com/assets/8423640/7740546/5a451e58-ffae-11e4-8ff9-2351e87d519e.png)
 "make uninstall", "rm -rf ~/XVim", then clone again.
I got this warning and "Load Bundle", "make", then succeeded.

**Comment by cdwind** [comment]
@mimaun I got same problem as you

**Comment by JessThrysoee** [comment]
Anyone know how to undo "Skip Bundle"?

**Comment by lando2319** [comment]
Uninstall and reinstall should do it.

**Comment by hidez** [comment]
hi,

close Xcode
$ cd ~/Library/Application\ Support/Developer/Shared/Xcode
rename directory Plug-ins to Plug-ins-foo
open Xcode
close Xcode
rename back Plug-ins-foo to Plug-ins
open Xcode

You can see dialog "Load Bundle", may be. Try it.

**Comment by JessThrysoee** [comment]
This worked: delete plugin and then "Build and Run" from within Xcode.

I was deleting and building from CLI which didn't work.

**Comment by yayoc** [comment]
@hidez This worked for me. Thanks.

**Comment by zld** [comment]
@hidez Thanks a lot.

**Comment by zld** [comment]
@hidez This worked for me, though there is still no XVim menu. Thanks a lot.

**Comment by hxx0215** [comment]
@hidez This worked for me, though there is still no XVim menu. Thanks a lot. +1 and ctrl-o not worked

**Comment by lando2319** [comment]
When I pulled I had to unmap my previously saved xcode mapping through the
xcode preferences. Once I did that it worked for me.

**Comment by hxx0215** [comment]
@lando2319 unfortunately it not worked for me .So I map <C-o> to :pj<cr> to solve this...

**Comment by JugglerShu** [comment]
So for everyone who can't load XVim correctly, please try following.
  - Uninstall current XVim plugin completely. (`> make uninstall` should do it.)
  - Confirm you uninstalled XVim correctly (Run Xcode and confirm XVim is not there). 
    If you find XVim is not uninstalled, find the plugin and delete it. (maybe you can use `find` command to find XVim.xcplugin in your filesystem.)
  - Pull latest master branch.
  - Make it by `> make`
  - Run Xcode 6.3.2
  - Press "Load Bundle" button when Xcode shows dialog with a message "Unexpected code bundle..."
    If you don't see this dialog, try the following command and then restart Xcode.
    `> defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.3.2`

@hxx0215 
And about ctrl-o. The implementation has changed. It is now more like Vim's jump list. Please create an issue if you find something is not your expectation.

**Comment by zhouzy** [comment]
@mimaun  This worked for me,thank you!

**Comment by yuuki1224** [comment]
My XVim has worked! Thank you so much! :+1:

**Comment by ducktypeian** [comment]
@JugglerShu this works for me, especially this one `defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.3.2`  
Thank you!

**Comment by bananatreedad** [comment]
@hidez worked for mee too! thx a lot.
