### ISSUE TITLE
(, ), {, } support

### ISSUE THREAD

**Issue by iluuu1994** [XVimProject/XVim#764]
In vim you can jump by sentence using `(`, `)` or by paragraph using `{`, `}`.
Support for that would be great!
##

**Comment by fespinoza** [comment]
:+1:

**Comment by JugglerShu** [comment]
Is this not working now?? 
This used to be working I think. Or the behaviour of this is not as you expected?

https://github.com/XVimProject/XVim/blob/master/Documents/Users/FeatureList.md

**Comment by fespinoza** [comment]
i saw that was on the feature list, 

as far as i know, in vim a paragraph is between empty blank lines

so `{` should allow me to

navigate between methods definitions since there is white lines between the code

but right now, just navigates between the beginning and end of a class

**Comment by joshcho** [comment]
} does not allow for moving across white lines in the code as of now!
