### ISSUE TITLE
Auto-completion popover and esc

### ISSUE THREAD

**Issue by iluuu1994** [XVimProject/XVim#765]
Something that bothers me a lot is that I often want to cancel the auto-completion popover by pressing the `esc` key. Unfortunately, this also makes the editor go into normal mode.

Is it possible to not exit the insert mode when pressing `esc` key if the auto-completion popover is opened?
##

**Comment by pebble8888** [comment]
Use Xcode shortcut 'Show completions '^ Space'.
When the popover window is showed, this shortcut hide it.

**Comment by iluuu1994** [comment]
Thanks, I'll try this. Nonetheless, I'd still like to see if @JugglerShu would think this is a good idea or not.

**Comment by JugglerShu** [comment]
Yea I also think we should handle `esc` not to escape from insert when completion is shown.
I have tried it once but I think I haven't done it and didn't merge.

**Comment by pebble8888** [comment]
Ah, that feature sounds good.
+1

**Comment by haaakon** [comment]
+1

**Comment by Phenmod** [comment]
+1
