### ISSUE TITLE
Xcode 7 beta support

### ISSUE THREAD

**Issue by rafalio** [XVimProject/XVim#772]
How can I get XVim to run in Xcode 7?

**Comment by aholub** [comment]
Same question. I tried putting the Xcode 7 UUID into the DVTPlugInCompatibilityUUIDs array in Info.plist, as recommended in other threads, but that didn't seem to work.

**Comment by coxy1989** [comment]
Ditto

**Comment by Coocoolaka** [comment]
Seems to work for me. I added XCode 7 UUID AABB7188-E14E-4433-AD3B-5CD791EAD9A3 into the DVTPlugInCompatibilityUUIDs array in XVim Info.plist (~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/Info.plist). Also have to reopen xcode.

**Comment by coxy1989** [comment]
Success. Cheers @Coocoolaka

**Comment by JugglerShu** [comment]
Now master and develop branch should work on Xcode 7 beta.
Although, it seems that XVim menu doesn't working correctly.

**Comment by rafalio** [comment]
Thanks, it is indeed working now on master! Thanks @Coocoolaka.

**Comment by mayqiyue** [comment]
Success. I love you! @Coocoolaka

**Comment by mayqiyue** [comment]
Success. I love you! But can u tell me how to find the UUID? @Coocoolaka

**Comment by Coocoolaka** [comment]
It is in the `Info.plist` in your Xcode app's `Contents` folder. For this case you can get by running the following command:
```
/usr/libexec/PlistBuddy -c 'Print DVTPlugInCompatibilityUUID' "/Applications/Xcode-beta.app/Contents/Info.plist"
```

**Comment by ssagawa** [comment]
add UUID

```
$ find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist | xargs -IFILE defaults write FILE DVTPlugInCompatibilityUUIDs -array-add AABB7188-E14E-4433-AD3B-5CD791EAD9A3
```

confirm
```
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist | xargs -IFILE defaults read FILE DVTPlugInCompatibilityUUIDs
```

and reopen Xcode 7.
in dialog select "Load Bundle".

It worked.
