### ISSUE TITLE
Cannot use GG to go to the end of file

### ISSUE THREAD

**Issue by lijingjiang** [XVimProject/XVim#783]
Hi, 

The problem is when I want to use the GG like vim to go to the end of the line, it will go to the head of the line just like gg. I have no idea that if there is a crash in hotkeys. Would you mind provide me with some hints.

Thank you.

**Comment by JugglerShu** [comment]
Which command are you talking about? `gg` should go to `head of file' . `G` should go to `end of file`.
Both of them are not about `lines`.

**Comment by lijingjiang** [comment]
Sorry for the confusion, I mean when I press the G it will locate at the head of the file (sorry, it is the head of the file not line) instead of the end of file. 

My system is Yosemite 10.10.2, my XCode version is 6.1 and I installed the Xvim plugin through the package manager.

Thank you.

**Comment by JugglerShu** [comment]
Can you try to clone and make XVim by yourself?
It is just like 

   - `git clone https://github.com/XVimProject/XVim
   - `cd XVim`
   - `make`

and restart your Xcode.

**Comment by lijingjiang** [comment]
Thank you! The problem was solved!
