### ISSUE TITLE
Indent using << and >> always produces spaces? [$50]

### ISSUE THREAD

**Issue by steinnes** [XVimProject/XVim#795]
Not sure if this is a real issue or just a configuration problem on my end, I have however tried to configure the tab/indent behaviour in my `~/.xvimrc` file, which now contains:

```
set shiftwidth=8
set noexpandtab
```

My XCode settings are basically to use `tab` characters for indentation, but display them as 4 spaces.  This could be accomplished in "vanilla" vim by just setting `tabstop=4` and `shiftwidth=4`, because pressing `>>` or `<<` would add or remove tab characters until meeting the shiftwidth.  In my case only one.

However with XVim I always get 4 spaces when I use the `<` and `>` keys to indent (I use this a lot when visually indenting blocks).

Am I missing something obvious (I am new to XCode, been using Vim for a while :-) ?

**Comment by ghthor** [comment]
+1 this issue, it's infuriating me to no end, down with spaces.

**Comment by ajylee** [comment]
I believe I solved this issue, in my [develop branch][]. See my commit:

    https://github.com/ajylee/XVim/commit/17fdb976ac6e05be6fbcf2dcfc76d57b469a9c8d

I hope it works for you.

[develop branch]: https://github.com/ajylee/XVim/tree/develop

**Comment by steinnes** [comment]
I have verified that the ajylee/add-expandtab-fixed branch works for me.
