### ISSUE TITLE
Missing `XVim` menu item in Xcode 6.4

### ISSUE THREAD

**Issue by comatory** [XVimProject/XVim#803]
I have issues where XVim sometimes stops working so I have to run `make` again. Anyways the menu item never reappeared in 6.4. What's the status on that? Thanks.
##

**Comment by fontno** [comment]
@comatory It's in the Editor menu dropdown at the bottom. You can enable/disable Xvim from there.


![xvimmenuitem](https://cloud.githubusercontent.com/assets/520619/9235654/a6680122-4105-11e5-92bd-0194b8ad4c91.png)

**Comment by lando2319** [comment]
For me the XVim option will also disappear sometimes, it seems to happen
after my comp has been in sleep mode. It's rare that I turn XVim off, but
the few times, I've had to restart XCode in order for the option to
reappear.

On Wed, Aug 12, 2015 at 3:22 PM Brian Fontenot <notifications@github.com>
wrote:

> @comatory <https://github.com/comatory> It's in the Editor menu dropdown
> at the bottom. You can enable/disable Xvim from there.
>
> [image: xvimmenuitem]
> <https://cloud.githubusercontent.com/assets/520619/9235654/a6680122-4105-11e5-92bd-0194b8ad4c91.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XVimProject/XVim/issues/803#issuecomment-130435198>.
>
-- 
Mike P Land - http://mikepland.com/
Independent Software Developer
Web & Mobile | JavaScript & Swift

**Comment by yixiang** [comment]
I think this breaks menu: #758

**Comment by comcxx11** [comment]
이게 뭐야 ???

2015년 9월 5일 토요일, yixiang<notifications@github.com>님이 작성한 메시지:
