### ISSUE TITLE
Customize color of Xvim bar.

### ISSUE THREAD

**Issue by jordwalke** [XVimProject/XVim#830]
The grey bar is somewhat jarring when using a different text editor color scheme. It would be good to be able to customize this, and by default grab some colors from the text editor theme.  For example, the gutter fold colors might be a good choice. As a further enhancement, I'm curious if xcode themes could allow a special field that tells XVim which color to render the status bar with.

**Comment by JugglerShu** [comment]
Please try the latest master. It should fix this.
