### ISSUE TITLE
How to reinstall XVim

### ISSUE THREAD

**Issue by roseperrone** [XVimProject/XVim#838]
After making XVim and opening Xcode, I accidentally clicked the "Do not install the plugin" or whatever the alert said when Xcode opened. I tried running make uninstall on XVim, closing Xcode, making XVim, setting "Reset 'Do Not Ask Me Again'" warnings in Xcode, and reopening Xcode, but XVim does not install.

**Comment by keith** [comment]
You can fix this by editing Xcode's plist. You can see what you need to edit with:

```
defaults read com.apple.dt.Xcode | less
```

In here there are keys formatted as:

```
DVTPlugInManagerNonApplePlugIns-Xcode-[XCODE-VERSION]
```

You can just delete the key corresponding to your Xcode version and Xcode will ask you about all bundles again. For Xcode 7:

```
defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.0
```

**Comment by roseperrone** [comment]
Awesome, thanks for the fast response!!
