### ISSUE TITLE
Not working on Xcode 7

### ISSUE THREAD

**Issue by GGMethos** [XVimProject/XVim#840]
I followed the instructions but when I open Xcode, nothing happens. It just launches normally. Any ideas?

**Comment by carrigmore** [comment]
Did you download the Xcode from git using git clone command? After that you need to goto Xcode folder and use make command to build the Xvim project. Then you launch the Xcode, you will see a pop up notification window saying detected third party plugin Xvim, and asking if you would like to use it, which means the plugin has been recognised by Xcode.

**Comment by lytzen** [comment]
I've done as described above, and it works fine, except when starting a playground. If I open a playground, Xcode crashes with the error: "Xcode quit unexpectedly while using the XVim plug-in"

A very small piece if trace info:
ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-8208/DVTKit/ViewControllers/DVTControllerContentView.m:368
Details:  <DVTControllerContentView: 0x7f91bcdc73a0> can only have one subview, its contentView

**Comment by GGMethos** [comment]
carrigmore, yes the build succeeded and everything. there is no notification window that shows up

**Comment by a9austin** [comment]
I am having the same issue.

**Comment by JugglerShu** [comment]
If you are not  able to launch Xcode with XVim try what I commented on #757 .

@lytzen 
I think the crash is due to the new restriction introduced in Xcode 7. I have to see it.

**Comment by a9austin** [comment]
Sweet I got it work by following your instructions

**Comment by GGMethos** [comment]
Thank you.
