### ISSUE TITLE
Crash when opening Playgrounds - Xcode 7.0.1. (7.1 seems OK?)

### ISSUE THREAD

**Issue by cjwirth** [XVimProject/XVim#846]
Nice tool, I enjoy using it.
However, Xcode 7.0.1 is crashing 100% every time I try to open a playground.

I'm using XVim build from the develop branch, commit  125c207a73d9f7584d52c2b6bd217f17ef327e20.

[Crashlog in a gist, because it's super long](https://gist.github.com/anonymous/9314795c1399cece9a48)

**Comment by cjwirth** [comment]
I've played around a bit, and got it to at least _not crash_. I still can't actually use XVim _inside_ the playground, and I have to disable XVim in order to actually edit anything inside the playground. But hey, it's not crashing.

_IDEPlaygroundEditor_ seems to be something new in Xcode 6, but not added yet to XVim. 

It is a subclass of _IDESourceCodeEditor_, and so [xvim_initWithNibName:bundle:document:](https://github.com/XVimProject/XVim/blob/develop/XVim/IDESourceCodeEditor%2BXVim.m#L30) gets called when it is loaded. 

However, the contentViews are different in this new _IDEPlaygroundEditor_ class. Instead of being `[[obj view] contentView]` it is actually at `[[[objc view] contentView] contentView]`. 

Then later when it gets the scrollView, that seems to have changed too. `[self mainScrollView]` returns nil. However, there is a scroll view at `[[container subviews] objectAtIndex:0]`, assuming that `container` is the container we fetched up above.

I know this isn't complete, and I know it's pretty messy, but hopefully it will point someone in the right direction. I changed the `xvim_initWithNibName...` to begin with this:

```Objective-C
- (id)xvim_initWithNibName:(NSString*)name bundle:(NSBundle*)bundle document:(IDEEditorDocument*)doc{
    id obj = [self xvim_initWithNibName:name bundle:bundle document:doc];
    NSView* container = [[obj view] contentView];
    if ([obj isKindOfClass:NSClassFromString(@"IDEPlaygroundEditor")]) {
        container = [[[obj view] contentView] contentView];
    }

    // Insert status line
    if( nil != container ){
        // TODO: Observe DVTFontAndColorSourceTextSettingsChangedNotification to change color of status bar
        DVTSourceTextScrollView* scrollView = [self mainScrollView];
        if ([obj isKindOfClass:NSClassFromString(@"IDEPlaygroundEditor")]) {
            scrollView = [[container subviews] objectAtIndex:0];
        }
        [scrollView setTranslatesAutoresizingMaskIntoConstraints:NO]; // To use autolayout we need set this NO
   ...
```

And it doesn't crash anymore. XVim still doesn't work in there. But it doesn't crash :)

**Comment by cjwirth** [comment]
It seems like this is working in Xcode 7.1!

**Comment by JugglerShu** [comment]
Please test develop branch.

**Comment by cjwirth** [comment]
Excellent, it seems to be working on my machine.

Thanks!
