### ISSUE TITLE
Does not work in XCode 7.1

### ISSUE THREAD

**Issue by rednebmas** [XVimProject/XVim#853]
After upgrading and attempting to reinstall, XVim does not work in XCode 7.1. I'm really bummed I upgraded!

**Comment by pitoneux** [comment]
Just add this in the info.plist in the list of keys and re-compile:

7265231C-39B4-402C-89E1-16167C4CC990

eric

**Comment by rednebmas** [comment]
Thanks!

**Comment by imavca** [comment]
Thanx!

**Comment by evanbrass** [comment]
+1

**Comment by mimaun** [comment]
Me too, it works fine! Thank you!

**Comment by gsheld** [comment]
I'm sorry, I believe I'm missing something. I updated `XVim/Info.plist` to [this](http://i.imgur.com/j9ltxyi.png) and re-ran "make". Opening Xcode did not prompt me to install the plugin nor was XVim functional.

Would appreciate some advice.

**Comment by hidez** [comment]
Hi, where you want to add the ID is incorrect.
You need add the id to array under "DVTPlugInCompatibilityUUIDs".

**Comment by gsheld** [comment]
> Hi, where you want to add the ID is incorrect.
> You need add the id to array under "DVTPlugInCompatibilityUUIDs".

@hidez Thanks for the clarification! It works now.
