### ISSUE TITLE
Cursor not visible Xcode 7.1

### ISSUE THREAD

**Issue by dylansm** [XVimProject/XVim#863]
I've tried several themes and it appears to be an issue on all of them. The cursor isn't visible but XVim commands seem to work e.g. dd to delete line. Installed using Alcatraz.

Update: this appears to only affect Playgrounds. Projects seem ok.

**Comment by JugglerShu** [comment]
1. Download the latest master branch and make it.
2. create .xvimrc file and wrihte `set blinkcursor`

This should fix it.

**Comment by dylansm** [comment]
Thanks. Setting blinkcursor on my already installed Alcatraz Xvim worked.

**Comment by mebmichael** [comment]
Awesome, thanks!
