### ISSUE TITLE
Command line messages are overdrawn

### ISSUE THREAD

**Issue by pebble8888** [XVimProject/XVim#864]
Command line messages are overdrawn.

type `*` at some word
message "/\binterface\b" show
type `
Shift-v`
message "-- VISUAL LINE --" is overdrawn.
Also, type `Ctrl-g`
message "/.../XVimCommandLine.m  line 21 of 387 --5%-- col 8" is overdrawn.

It occur in master and develop branch.
Xcode7.1 and 6.4
MacBookAir 2015

I'm using `laststatus=0`

![2015-10-26 20 54 08](https://cloud.githubusercontent.com/assets/1704383/10728297/ebfed964-7c23-11e5-8adf-0543916099f5.png)

**Comment by JugglerShu** [comment]
Please test develop branch. Let me know if it still has any problem.

**Comment by pebble8888** [comment]
Thanks. I confirmed the issue is fixed for static message.
I will send pull request for error message.

**Comment by pebble8888** [comment]
Fixed.
