### ISSUE TITLE
Normal mode cursor vanishes, Xcode 7.1

### ISSUE THREAD

**Issue by mebmichael** [XVimProject/XVim#866]
After upgrading to Xcode 7.1, I can no longer see the block cursor (or any indication of a cursor for that matter) when in normal mode. As soon as I step into insert mode, the insert cursor becomes visible, so this is my only hopes for movement around the text, aside from a mouse. However, I can still do the usual delete, yank, etc. in normal mode, I just can't tell which line I'm on or where I am on the line. I tried reinstalling the plugin, restarting the Xcode, restarting the computer, all of this several times, to no avail. Is anyone else experiencing this?

**Comment by JugglerShu** [comment]
#863

**Comment by JugglerShu** [comment]
The develop branch should fix this. Please check.

**Comment by JugglerShu** [comment]
Merged to master.
