### ISSUE TITLE
Large white areas while scrolling

### ISSUE THREAD

**Issue by GregIngelmo** [XVimProject/XVim#867]
Just upgraded to XCode 7.1, ran make at a380c94504c6f03df7ad8bc30283898500a8dba9

![screen shot 2015-10-26 at 11 31 36 pm](https://cloud.githubusercontent.com/assets/348608/10748769/cfef45a4-7c39-11e5-933a-71349170d56f.png)
##

**Comment by GregIngelmo** [comment]
Confirming #870 , updated screenshot 
<img width="1440" alt="screen shot 2015-10-27 at 8 10 40 am" src="https://cloud.githubusercontent.com/assets/348608/10757852/e0c74882-7c83-11e5-96ee-281ae1e18846.png">

**Comment by JugglerShu** [comment]
How do you get this ? just open Xcode? Any operation?

**Comment by GregIngelmo** [comment]
To repro the characters being rendered in the top area of XCode:
1. Place cursor somewhere in Normal mode
2. Run project (I'm using the sim)
3. Scroll with the trackpad, up or down a full page

The character that is you left the cursor on while be repeated into the top (and sometimes bottom) area of XCode.

Example vid:
https://dl.dropboxusercontent.com/u/330001/xvim_xcode_7_1_issue.mp4

**Comment by GregIngelmo** [comment]
I can't consistently repro the appearance of the large white blocks yet. Seems to only happen after I've had a particular file open for a few minutes.

**Comment by GregIngelmo** [comment]
Relevant OSX / XCode info

```sh
$ sw_vers -productVersion
10.11.1

$ xcodebuild -version
Xcode 7.1
Build version 7B91b

$ xcrun swift -version
Apple Swift version 2.1 (swiftlang-700.1.101.6 clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
```

**Comment by GregIngelmo** [comment]
To repro the white blocks you just have to scroll up and down a lot.

Ex:
https://dl.dropboxusercontent.com/u/330001/xvim_scode_7_1_white_issue.mp4

**Comment by JugglerShu** [comment]
I'm seeing you have horizontal scrollbar at the bottom of the source view. It may be because of it. I'll check it.

**Comment by luomuwen** [comment]
follow this issue

**Comment by JugglerShu** [comment]
I can't reproduce this large area white blank. I can wee #870 but not this one.  I have tried several scroll bar setting including XVim and Max general setting.
I haven't installed Mac 10.11 so it might be because of it...

**Comment by GregIngelmo** [comment]
In my case the problem went away after I set "show scroll bars" to automatic. But it does come back if I re-enable it.

**Comment by mayqiyue** [comment]
Subscribe this issue.

**Comment by JugglerShu** [comment]
I still cannot reproduce this problem. Can you try the latest develop branch? It fixes several problems related to UI rendering. I don't know if these fixes this problem but possibly fix this...

**Comment by GregIngelmo** [comment]
Will do

**Comment by GregIngelmo** [comment]
Unfortunately no, the latest dev HEAD doesn't change this issue. I changed Settings->General->Show Scrolll bars to "Always"... After about 2 minutes the white areas started appearing again (as in the earlier videos).

**Comment by JugglerShu** [comment]
@GregIngelmo 
Hm... I really can't reproduce this white area... I set the scroll bar setting "Always" and I see the almost the same appearance of your movie. I tried to scroll up, down repeatedly fast but I can't see such white area... 
As far as I see the movie, the area is just rendering problem. I mean if you trigger re-draw event in some way the white area goes away, right?
It maybe because of the machine power or difference of rendering system.
I'm using 10.11.1 now but still can't reproduce.

If anyone else can reproduce this please let me know and give me your environment information.

**Comment by floorish** [comment]
Not sure if related, but I often get repeated patterns when I scroll up or down (instead of white blocks). 

![screen shot 2015-11-10 at 10 41 57](https://cloud.githubusercontent.com/assets/623528/11059103/e9a41470-8797-11e5-82e0-daabca3c5c8d.png)

Once the cursor is moved (either by mouse click or vim movement) the code is rendered correctly.

Xcode: Version 7.1 (7B91b)
OSX: Version 10.10.5 (14F27)
XVim: latest develop (26bdd1a3) and Alcatraz version 
XVimrc: https://github.com/floorish/dotfiles/blob/master/xvimrc
No other plugins loaded

**Comment by GregIngelmo** [comment]
@floorish Interesting, I experience the same behavior you describe, "Once the cursor is moved (either by mouse click or vim movement) the code is rendered correctly", that's exactly how I fix the white areas.

@JugglerShu 
>As far as I see the movie, the area is just rendering problem. I mean if you trigger re-draw event in some way the white area goes away, right. 

Yes exactly.

Are there any debugging options I can turn on to help trouble shoot this on my end?

**Comment by GregIngelmo** [comment]
@floorish Are you using a custom font?

**Comment by floorish** [comment]
@GregIngelmo I don't think it's a custom font, it's Menlo Regular - 13.0.

**Comment by GregIngelmo** [comment]
Ok, just a hunch. I wonder if there's something in our XCode configurations that manifests itself in these rendering artifacts (white bars on mine, smeared text on yours)

**Comment by floorish** [comment]
After some more testing it seems that the smeared text problem does not occur when I set scrollbars to always on. (It comes back when I set scrollbars to automatic)
This is exactly the opposite of what fixes the white area problem that you have @GregIngelmo ...

**Comment by apollow** [comment]
@floorish
How would you set the scrollbars to always on? I'd love to know!

**Comment by GregIngelmo** [comment]
@apollow It's in system settings https://github.com/XVimProject/XVim/issues/870#issuecomment-152292626

**Comment by apollow** [comment]
@GregIngelmo 
Settings - System Preferences -> General -> Show scrollbars: Always
did the trick, cheers!

**Comment by JugglerShu** [comment]
While I was debugging about #882 I happened to reproduce this problem.
These two bugs seems *not* the same problem.

Unfortunate thing is that I cannot reproduce this white area bug in debugging session.
I also don't know how certainly reproduce this...
