### ISSUE TITLE
XCode 7.1 , mess render issues

### ISSUE THREAD

**Issue by sunuslee** [XVimProject/XVim#870]
<img width="1512" alt="screen shot 2015-10-27 at 14 33 48" src="https://cloud.githubusercontent.com/assets/584417/10751112/1372fd10-7cb8-11e5-9e4a-fed68f2573dc.png">

**Comment by sunuslee** [comment]
__i do not modify the screenshot at all.__
the white area in file path area , the strange '}' characters , etc... 
looks like the refresh didn't take place.

**Comment by evanwalsh** [comment]
I am seeing this as well. Whatever character is highlighted renders outside of the text view when you scroll it.

**Comment by GregIngelmo** [comment]
@evanwalsh When you scroll up and down do you see white areas (as in #867)?

**Comment by evanwalsh** [comment]
@GregIngelmo I do not

**Comment by loveforgeter** [comment]
I have the same problem as well as white areas

**Comment by andrewschreiber** [comment]
I'm having a similar issue in Xcode 7.1.
![screen shot 2015-10-28 at 10 27 19 am](https://cloud.githubusercontent.com/assets/1892071/10797159/914493e2-7d5e-11e5-96cd-82f7cbeca70b.png)

**Comment by GregIngelmo** [comment]
@loveforgeter In Settings->General I had "Show scroll bars" set to "Always". I set it back to Automatic and the white areas are no longer appear.

**Comment by sunuslee** [comment]
@GregIngelmo can you please  post a screen about that setting "Show scroll bars" ? because i dont find that in  Settings->General.
thank you!

**Comment by loveforgeter** [comment]
@sunuslee I didn't find the settings either, write 'set guioptions=r' to you ~/.xvimrc file,that works

**Comment by GregIngelmo** [comment]
@loveforgeter @sunuslee 

<img width="668" alt="screen shot 2015-10-29 at 3 17 02 pm" src="https://cloud.githubusercontent.com/assets/348608/10829462/7c3f6c86-7e50-11e5-852a-726f7717f428.png">

**Comment by sunuslee** [comment]
@GregIngelmo i've already have 'Automatically based on mouse or trackpad' checked. but nothing changes.

**Comment by neybis** [comment]
It's worth pointing out that I'm seeing this a decent amount of time in Xcode 6 as well. I am running off of the head of develop branch.

**Comment by mayqiyue** [comment]
@GregIngelmo :I set to "When scrolling". works!

**Comment by apshoemaker** [comment]
I can confirm that setting "Automatically based on mouse or trackpad" did NOT fix the issue for me.

XCode Version 7.1 (7B91b)
XVim HEAD
OS X 10.11.1

**Comment by xnxin** [comment]
@apshoemaker  the same as you

**Comment by GregIngelmo** [comment]
@apshoemaker @xnxin So after changing the setting in the screenshot to "automatic" or "while scrolling" you still see the white bars while scrolling? (note this *doesn't* fix the characters rendering at the top/bottom)

**Comment by JugglerShu** [comment]
The develop branch should fix this problem (not for large white area problem). Please check.

**Comment by GregIngelmo** [comment]
Confirmed fix. The characters no longer appear at top and bottom.

**Comment by xnxin** [comment]
there is still has the problem, i just use the Xcode 6.3 to complier it don`t work ,and i use the makefile ,it don`t work either. it always appear on the top with a character. i just want to know how to fix it

**Comment by JugglerShu** [comment]
@xnxin 
Please confirm following things.
  - Uninstall previous version first ( make uninstall should do it )
  - Build **the latest develop** branch
  - **Restart** Xcode
 
If you still have problem, please upload your screen capture here.

**Comment by xnxin** [comment]
<img width="795" alt="xvim issue" src="https://cloud.githubusercontent.com/assets/10513841/11055927/1118ba0a-87b7-11e5-8b32-1ab389771bfe.png">
I`ve try compiler with Xcode 6.3.1 with release,and the Xcode 7.1 complier ,but it`ll also mess up with character. it is better than before

**Comment by JugglerShu** [comment]
So how did you get the source code after you changed the branch to `develop` in github web page? Download ZIP file??

**Comment by xnxin** [comment]
I just Click the Clone with the github Desktop,and reinstall the xvim

**Comment by xnxin** [comment]
I just  download the zip file with the develop branch , it`s work perfect now, may be i should learn how to use the github. thanks !

**Comment by JugglerShu** [comment]
@xnxin 
Good. So usually you don't use the github web page to change branch. Here's how.

 1. Clone the repository. `> git clone https://github.com/XVimProject/XVim`
 2. Go into the cloned dir. `> cd XVim`
 3. Checkout develop branch. `>git checkout develop`
 4. Then build `> make`

This is really basic when you use git and github so try to use these next time.

**Comment by sunuslee** [comment]
@JugglerShu cool thanks!  awesome!
