### ISSUE TITLE
Xcode 7.1 Playgrounds not showing evaluation on right

### ISSUE THREAD

**Issue by dylansm** [XVimProject/XVim#874]
When I have the XVim plugin installed, a new default Playground should show "Hello, playground" on the right. It doesn't. When I uninstall the plug-in, it shows on the right, as expected.

This is the simplest example. Fact is, nothing evaluates on the right when the plug-in is installed.

**Comment by GregIngelmo** [comment]
Same here

**Comment by kouky** [comment]
:+1: new playground with "Hello World", nothing printed by the REPL. Remove Xvim and the REPL starts printing again.

**Comment by mudox** [comment]
Confirmed

**Comment by eriknelson** [comment]
+1 here, xvim definitely breaks the playground eval.

**Comment by oldMrCoder** [comment]
+1

**Comment by skf321** [comment]
lucky to find a answer here

**Comment by stoneros** [comment]
Confirmed!

**Comment by JugglerShu** [comment]
I have investigated this problem. I already know rough reason of this problem but still don't know how to really fix this without disabling XVim.
Since I have to write some new methods to override default Playground behavior it may take a little time.
Sorry for waiting.

**Comment by ZillaG** [comment]
How can I disable XVim temporarily?

**Comment by JugglerShu** [comment]
Simply you can't (to workaround this problem).

**Comment by zef** [comment]
@ZillaG you can temporarily move the `XVim.xcplugin` file from the `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/` directory to another location (like just up a folder or something), then re-launch Xcode. To reinstall just move it back and relaunch.

**Comment by ZillaG** [comment]
Ok I'll do that. Disabling it (Editor->XVim->toggle eneable/disable) doesn't work since the plugin is still there. Thanks.

**Comment by JugglerShu** [comment]
I made the temporary fix for this problem. Use develop branch for now. It still has several problems but should fix right pane problem in playground. Please use `set blinkcursor` workaround for cursor problem.

**Comment by zef** [comment]
@JugglerShu you are amazing! Thank you so much for all your hard work!

**Comment by JugglerShu** [comment]
I don't use Playground much so I can't recognise what is not usual in Playground. So please report if you still have any critical problems in Playground.

**Comment by kouky** [comment]
@JugglerShu thanks so much for all your amazing work :sparkles:

**Comment by ZillaG** [comment]
Thanks!

(Sent from my iPhone)

**Comment by GregIngelmo** [comment]
Confirmed fix. Evaluations appear on the right again
