### ISSUE TITLE
XVim not loading with Xcode 7.1

### ISSUE THREAD

**Issue by davidquon** [XVimProject/XVim#877]
I pulled XVim `master` and built using `make`.  I opened Xcode `7.1` and accepted the external plug-in's when prompted however XVim didn't load and I am stuck Vim-less (gasp!).

**Comment by davidquon** [comment]
I noticed that my `Alcatraz` plug-in wasn't working either and tried removing both `Alcatraz` and `XVim` and re-installing to no avail.  I then came across this that saved the day for both `Alcatraz` and `XVim`.
https://github.com/supermarin/Alcatraz/issues/362#issuecomment-150457101

For those who don't want to click through here's the comment from @uptownboy :beer: :tada:.

```
problem fixed!!!!

run these 2 lines in terminal:
1:
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add defaults read /Applications/Xcode.app/Contents/Info.plist DVTPlugInCompatibilityUUID

2:
defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1

3:
restart xcode!
```

**Comment by jakecraige** [comment]
Worked for me. Thans!

**Comment by ScorpiusZ** [comment]
have the same problem with you, download Xvim __master__ and __make__ ,then restart xcode, but xvim seems not work, i have xcode version __7.1.1__
i have tried running two command in terminal , and it's still not working

**Comment by JugglerShu** [comment]
Try this. (You have to change the `version` part)
https://github.com/XVimProject/XVim/issues/757#issuecomment-106301119

**Comment by ScorpiusZ** [comment]
@JugglerShu  Thanks, It works for me

**Comment by davidquon** [comment]
Had the same problem upgrading from Xcode 7.2.1 to Xcode 7.3.  Deleting `XVim.xcplugin` and rebuilding `master` then running this command fixed it for me.
```
defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.2.1
```
Don't forget to restart Xcode afterwards and press "Load Bundle" button when Xcode shows dialog with a message "Unexpected code bundle..." (from https://github.com/XVimProject/XVim/issues/757#issuecomment-106301119).  Thanks @JugglerShu for the great plugin and helpful advice.
