### ISSUE TITLE
Cannot compile last version

### ISSUE THREAD

**Issue by savitskiyvm** [XVimProject/XVim#879]
When I run make, i got these errors:

====================
/Users/svm/Documents/Github/XVim/XVim/IDESourceCodeEditor+XVim.m:17:9: fatal error: 'NSobject+ExtraData.h' file not found
#import "NSobject+ExtraData.h"
        ^
1 error generated.
<..>
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/svm/Library/Developer/Xcode/DerivedData/XVim-fnladrvlpfzvmqezlzblfhblgcsq/Build/Intermediates/XVim.build/Release/XVim\ for\ Xcode5\ and\ 6.build/Objects-normal/x86_64/IDESourceCodeEditor+XVim.o XVim/IDESourceCodeEditor+XVim.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make: *** [release] Error 65

============================
After that i checked out commit b5bf219653d12131d893b5e4607e34541bc05156 and make works well on it.

**Comment by JugglerShu** [comment]
The latest master and develop branch should fix this. Please check.

**Comment by JugglerShu** [comment]
I consider it is fixed. Please reopen if you still have problems.
