### ISSUE TITLE
XVim breaks Playground

### ISSUE THREAD

**Issue by ZillaG** [XVimProject/XVim#881]
I use the XVim plugin, and it works perfectly in an IOS project. However, when in a Playground project, it has at least the following consequences (there may be more)
- Cursor is not shown
- Statements are NOT evaluated, and hence result not shown in right pane.

**Comment by ZillaG** [comment]
The second problem reported in this issue is a dup of #874

**Comment by JugglerShu** [comment]
The latest 'develop' branch should fix these problems. Please check.

**Comment by GregIngelmo** [comment]
Confirmed fix, latest dev branch fixes both issue for me.

**Comment by JugglerShu** [comment]
Merged to master.
