### ISSUE TITLE
219G goes to end of file instead of line 219

### ISSUE THREAD

**Issue by brianhv** [XVimProject/XVim#884]
I have a Swift file with 261 lines in it. When I type 219G, the cursor goes to the end of the last line in the file instead of line 219. The same thing happens with 211G and 215G, but all other lines between 210 and 225 appear to work correctly.

I'm using Xcode 7.1 (7B91b). I just rebuilt XVim from master and the issue is still present.

**Comment by JugglerShu** [comment]
I think this is the same as #865.
I'm fixing it now. Let me know if it's not the same problem.

**Comment by JugglerShu** [comment]
This should be fixed in `develop` branch now. Please check it. If it doesn't fix your problem, describe your problem here.

**Comment by brianhv** [comment]
I think that was indeed the problem I was having. Can no longer reproduce from the `develop` branch.
