### ISSUE TITLE
gg goes to bottom in Assistant Editor

### ISSUE THREAD

**Issue by zld** [XVimProject/XVim#885]
Works well in main editor, but goes to bottom in assistant editor.

**Comment by JugglerShu** [comment]
Which branch are you using? I have just fixed a problem related to `gg` in develop branch yesterday. Try that one and see if the problem fixed.

**Comment by zld** [comment]
@JugglerShu 
I was using `master` branch. I saw you just merged from `develop` and I pulled the latest code, it works fine now. 
Thanks a lot.
