### ISSUE TITLE
How to delete XVim menu keybinding?(CMD+SHIFT+X)

### ISSUE THREAD

**Issue by dabing1022** [XVimProject/XVim#887]
Hey, guys, How to delete XVim menu keybinding?(CMD+SHIFT+X)

To avoid key binding conflicting, I want to unbinding xvim's enable/disable. How can I do this? 

Thanks.:]

**Comment by JugglerShu** [comment]
I added feature to change XVim keyboard shortcut via preference. Please try develop branch. Let me know if it doesn't work as expected.

**Comment by JugglerShu** [comment]
Close this. Please reopen if you still have any problem.
