### ISSUE TITLE
Not working in Xcode 7.1.1

### ISSUE THREAD

**Issue by yuanlizbyy** [XVimProject/XVim#888]
I try to install XVim through `make` and manual build in Xcode 7.1.1 (7B1005), but it's still not working. Please fix this issue, thanks.

**Comment by yuanlizbyy** [comment]
cd Library/Application\ Support/Developer/Shared/Xcode
mv Plug-ins Plug-ins_
open Xcode
close Xcode
mv Plug-ins_ Plug-ins
open Xcode

Then it's done~

**Comment by jaunesarmiento** [comment]
Happened to me with Xcode 7.2. Shouldn't this be part of the README?

**Comment by jaunesarmiento** [comment]
Thanks for the tip @yuanlizbyy
