### ISSUE TITLE
Xcode code folding ribbon was effected by XVim

### ISSUE THREAD

**Issue by LiuPengBty** [XVimProject/XVim#892]
When i install the plugin by Alcatraz, the Xcode can't folding ribbon code. 
that's the image:
![f5fc6931-553b-4df3-9a0b-7f40fed46baf](https://cloud.githubusercontent.com/assets/15358037/11437826/ac3ea8ec-952b-11e5-9a3c-658627120404.png)

**Comment by petpwiuta** [comment]
i have seem issue.finally i disable this feature
<img width="602" alt="screen shot 2015-12-22 at 2 14 34 pm" src="https://cloud.githubusercontent.com/assets/4753810/11949083/7673792e-a8b6-11e5-977b-6fcf8646bf5a.png">
.

**Comment by DanielAsher** [comment]
I can confirm this fix. Should this be merged into master and closed?
