### ISSUE TITLE
Status bar covered up in Visual Line Mode

### ISSUE THREAD

**Issue by squarefrog** [XVimProject/XVim#893]
When using Visual Line Mode the status bar doesn't get cleared properly. Steps to reproduce:

1. Enter visual mode with `shift+V`
2. Select a block of text
3. Enter command mode with `:`
4. Observe 'VISUAL LINE' covering status bar, as shown below

![screenshot 2015-11-27 10 12 34](https://cloud.githubusercontent.com/assets/343450/11438823/680682f8-94ef-11e5-9ba2-fc78cd78fe7c.png)

-----

Xcode 7.1.1
Xvim latest develop branch

* `make uninstall`
* `git checkout develop`
* `make clean-release`
* `make release`
* Restart Xcode

**Comment by squarefrog** [comment]
This also affects standard visual mode. A quick and dirty patch is to just set the background colour of the `_command` text view in `XVimCommandLine`.

    diff --git a/XVim/XVimCommandLine.m b/XVim/XVimCommandLine.m
    index 35b48b5..88c2a18 100644
    --- a/XVim/XVimCommandLine.m
    +++ b/XVim/XVimCommandLine.m
    @@ -46,6 +46,7 @@ -(void)updateFontAndColors{

             [_command setFont:textFont];
             [_command setTextColor:textColor];
    +        [_command setBackgroundColor:textBackgroundColor];
             [_command invalidateIntrinsicContentSize];

             [_argument setFont:textFont];
    @@ -195,7 +196,7 @@ - (id)init
             _command = [[XVimCommandField alloc] init];
             [_command setEditable:NO];
             [_command setSelectable:NO];
    -        [_command setBackgroundColor:[NSColor clearColor]];
    +//        [_command setBackgroundColor:[NSColor clearColor]];
             [_command setHidden:YES];
             [_command setTranslatesAutoresizingMaskIntoConstraints:NO];
             // Width

Ideally, there should be some sort of observing on this value. Something like the following:

    if (_command.string != nil && [!_command.string isEqual: @""]) { 
        _static.hidden = YES
    } else {
        _static.hidden = NO
    }   

However it looks as if `[_command setString:]` is called outside of the `XVimCommandLine` class.

**Comment by kapsy** [comment]
Still no fix?

**Comment by squarefrog** [comment]
Yes theres a fix waiting in PR #894

**Comment by kapsy** [comment]
Goody. Thank you!
