### ISSUE TITLE
Cursor Disappeared in Swift Playground (Normal Mode)

### ISSUE THREAD

**Issue by BigPa** [XVimProject/XVim#895]
Xcode Version 7.1.1(7B1005)
OS X El Capitan 10.11.1

**Comment by JugglerShu** [comment]
Get the latest version.

**Comment by BigPa** [comment]
I got the latest version, and the issue still exist.


<img width="807" alt="2015-12-01 12 47 45" src="https://cloud.githubusercontent.com/assets/9963287/11492642/e4fffe04-982a-11e5-9950-ec0f783c4094.png">

**Comment by JugglerShu** [comment]
Write how you get the latest version and how you build it.  I think you are still using older version. It is already fixed and I can't reproduce it now)

**Comment by BigPa** [comment]
My fault, I forgot to make :flushed:

**Comment by BigPa** [comment]
My fault, I forgot to make :flushed:

**Comment by BigPa** [comment]
My fault, I forgot to make :flushed:
It's already fixed

**Comment by BigPa** [comment]
- git clone - make
I forgot 2nd step, just make.

Patrick Wang patrickwang1024@gmail.com
via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.12.43&pv=9.3.2&source=email_footer_2]
On 周四, 7月 14, 2016 at 02:03, NextSeason <notifications@github.com> wrote:
@BigPa [https://github.com/BigPa] Can you tell me the approach for fix it?
