### ISSUE TITLE
Xvim not working for code 7.2

### ISSUE THREAD

**Issue by HSadhotra** [XVimProject/XVim#899]
The plugin's amazing work.
However it's not working for Xcode 7.2. Just downloaded and ran "make". xvim was not enabled in Xcode

Thanks for all the help

Cheers
Harish

**Comment by keith** [comment]
It will once https://github.com/XVimProject/XVim/pull/898 is merged.

**Comment by ciryon** [comment]
@keith just tested your pull request and it seems to work, thanks!

**Comment by HSadhotra** [comment]
How do I merge? Is it possible to provide instructions?

**Comment by HSadhotra** [comment]
Never mind, I added the row in plist and it's working now (would love to know git instructions to do that, if any).
Thanks for all the help.
