### ISSUE TITLE
What is the right use manner for xvim's register?

### ISSUE THREAD

**Issue by JadianZheng** [XVimProject/XVim#913]
I want to yank some string in the `ayy`, but when I use `"ay`, it seem no work

**Comment by JugglerShu** [comment]
Write actual command you used. `ayy` inserts `yy` in the text since `a` goes into insert mode.
`"ay` is not complete command. It should be something like `"ayy` or `"ayw`.

`"ayy` and `"ayw" are working in my environment.

**Comment by JugglerShu** [comment]
I close this. Reopen this if you still have problem.
