### ISSUE TITLE
Would implementing the cmdline as a popup window make things easier.

### ISSUE THREAD

**Issue by mudox** [XVimProject/XVim#916]
The emulation of command line as an embedded area at the bottom of content window like vim makes a mess when I enable Editor -> Show Rendered Marker.
I suppose the embedding way brings a lot of interaction logic to the XVim codebase. Would making it an individual popup window eases this pain? Just popup it, with a bar of textfield,  when user press `:` in normal mode ...
Also it would make the XCode UI seem unhacked.
And also would the this UI division make XVim more robust against future XCode evolving.
Forgive me if I think of it too simple.

**Comment by JugglerShu** [comment]
Sorry for late reply. Yea that is one thing. But even you have a separate window, you still have to deal with the position of the window not to overwrap something important in the display. I think both has pros and cons. I do like that cmdline is at solid position as vim does. I'll think about it as an option if I have enough time.
