### ISSUE TITLE
Getting the error The domain/default pair of (/Library/Developer/CommandLineTools/../Info, DVTPlugInCompatibilityUUID) does not exist

### ISSUE THREAD

**Issue by arunabhdas** [XVimProject/XVim#920]
Running on Mac OS X Yosemite. Cloned repo and ran make. Getting the following message 

==> make
2016-01-16 03:40:58.107 defaults[99406:1108951] 
The domain/default pair of (/Library/Developer/CommandLineTools/../Info, DVTPlugInCompatibilityUUID) does not exist

**Comment by JugglerShu** [comment]
What is your Xcode version and did you install command line tools for Xcode??

**Comment by JugglerShu** [comment]
To make the 'makefile' work, `xcode-select` command must gives the proper Xcode path.
What `xcode-select -p` shows in you environemnt?

**Comment by donut** [comment]
```
[I] ~                                                                           
↪ xcode-select -p                                                     0@12:22:40
/Library/Developer/CommandLineTools
```

**Comment by JugglerShu** [comment]
Sorry for late reply. Then try to do this.

      $ xcode-select -s [Your Xcode.app Path]/Contents/Developer
      (In my case, it is "xcode-select -s /Applications/Xcode.spp/Contents/Developer" )
Then run `make`

**Comment by donut** [comment]
Actually, with the upgrade to OS X 10.11.4 and Xcode 7.3 final, `make` worked fine.
