### ISSUE TITLE
Can I translate the README.md into Chinese?

### ISSUE THREAD

**Issue by liaohuqiu** [XVimProject/XVim#923]
I love `XVim`, can I translate the `README.md` into Chinese?

**Comment by JugglerShu** [comment]
Yes of course. Just send a PR. But plz consider maintainability since I can't edit Chinese. If you think you cannot keep maintaining the file, make it as simple as you can.

**Comment by JugglerShu** [comment]
I close this. If you still have any questions, just reopen this.

**Comment by Ryannnnnnn** [comment]
Any progress?
