### ISSUE TITLE
XVim not reading .xvimrc remaps

### ISSUE THREAD

**Issue by adudenamedruby** [XVimProject/XVim#945]
# Description

Seems Xcode is not reading some remaps of my .xvimrc. For example: it reads  "set blinkingcursor" but NOT "inoremap qj <Esc>" or "nnoremap <C-j> <C-w>j"
# Operation

Installed XVim through both Alcatraz AND manual build. Same problem.
# Expected behaviour

Want to map qj to <Esc>, <C-j/k/h/l> to move between editors, respectively, etc
# Environments
- Xcode Version [  7.3  ]
- XVim branch and revision [  master   ]
- Keyboard Language [  master   ]
- Input source language [  master  ]
# Crash log (if any)

```
 None available.
```
##

**Comment by pebble8888** [comment]
I can't reproduce the issue in my environment.
```
inoremap qj <Esc>
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
```

Clear your .xvimrc and put these command only and try.

**Comment by adrianbrink** [comment]
This should be closed.
