### ISSUE TITLE
[Discussion] Xcode 8 extension

### ISSUE THREAD

**Issue by squarefrog** [XVimProject/XVim#965]
The new [Xcode](https://developer.apple.com/xcode/) announced at WWDC '16, sounds like it could be promising for the future of XVim.

> New Xcode extensions for the source editor let you customize your coding experience. Use extensions to navigate within your editor’s text, and select, modify, and transform your code. 

I wonder if this means XVim could be leveraged as a first class citizen?

**Comment by JugglerShu** [comment]
Hm... I wonder how much flexibility the extension has.  
I think Vim's text manipulations could be implemented by it but 
we have something like commnad line, visual mode, recording...

I think the extension is anyway loaded as a kind of dynamic library and we can do anything if we are in the same process of Xcode eventually.

I still don't know what is the best way to utilize it but anyway I have to do something for Xcode 8.

**Comment by squarefrog** [comment]
Details are scarce right now, but it's definitely something to keep an eye on.

**Comment by haaakon** [comment]
We have to give feedback to the XCode engineers. If XVim is not possible for XCode 8 i'm leaving XCode for maybe AppCode. XCode is unusable without Vim mode!

**Comment by squarefrog** [comment]
Oh it seems there is already an issue for this here https://github.com/XVimProject/XVim/issues/964

I'll close this as a duplicate.
