### ISSUE TITLE
XCode8 beta6 only show caret highlight when moving it

### ISSUE THREAD

**Issue by shuoshi** [XVimProject/XVim#981]
# Description

when moving caret using j k or mouse, XVim hide whole line except caret
# Expected behaviour

show whole line, as u can see the screenshot I made, the line with caret hide all character except itself.
# temp fix

DVTSourceTextView+XVim.m
I comment line 230 and 231, and XVim works again, but I don't know is there any side effect for this. 
# Environments
- Xcode Version [  XCode8 beta6  ]
- XVim branch and revision [   master  ]
- Keyboard Language [  en   ]
- Input source language [  en  ]

![2016-08-21 6 41 08](https://cloud.githubusercontent.com/assets/1700820/17834259/51addcb0-676a-11e6-801b-2d487612ce8c.png)
##

**Comment by tuchangwei** [comment]
I also met the issue on Xcode7.3, I will try your temp fix, thanks.

**Comment by machinefixer** [comment]
same issue, how to get rid of this without temp fix?

**Comment by ambujpunn** [comment]
I'm seeing this on Xcode 8.1 as well

**Comment by ambujpunn** [comment]
@shuoshi what lines did you comment? i have an updated version of xvim so i dont see anything in line 230 and 231

**Comment by ambujpunn** [comment]
Can someone help with this? I can't use xvim because of this recurring bug

**Comment by shuoshi** [comment]
@ambujpunn I'll have a look

**Comment by shuoshi** [comment]
@ambujpunn the latest code of master has already commented         
    [self _drawInsertionPointInRect:rect color:color];
I compiled it and everything works fine

**Comment by ambujpunn** [comment]
@shuoshi Thanks for letting me know! I hadn't pulled from the latest
