### ISSUE TITLE
Not working with a clean install of macOS Sierra and Xcode 8

### ISSUE THREAD

**Issue by plm75** [XVimProject/XVim#995]
# Description
Clean install of macOS Sierra this morning then downloaded and installed Xcode 8.   Followed installation steps (code resign then make).  Xcode launches but xvim isn't activated; no message about loading bundles after launch.

Could anybody confirm this is working with macOS Sierra final and Xcode 8 final ?

# Operation
Followed instructions in INSTALL_Xcode8.md
git cloned xvim
sudo make
launch Xcode: no message about unknown bundles; Xcode works but Xvim not activated

# Expected behaviour
Xvim should work

# Environments
  - Xcode Version 8.0 (8A218a)
  - XVim branch and revision master c26bc50  
  - Keyboard Language US en
  - Input source language en

# Crash log (if any)
   
     [ Paste the log here ]

**Comment by JugglerShu** [comment]
Several things to confirm.
1. What do you see when you execute

       codesign -dv  /Applications/Xcode.app

2. Is you xcode-select set properly? Confirm it points to Xcode 8.

      xcode-select -p

3. You don't need "sudo" when you make. Remove your XVim built by "sudo" and re-make it without "sudo"

**Comment by plm75** [comment]
@JugglerShu 

On a new clean install:

Before signing, `codesign -dv  /Applications/Xcode.app` outputs:

Executable=/Applications/Xcode.app/Contents/MacOS/Xcode
Identifier=com.apple.dt.Xcode
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=242 flags=0x2200(kill,library-validation) hashes=3+5 location=embedded
Signature size=4167
Info.plist entries=36
TeamIdentifier=xxxxxxxx
Sealed Resources version=2 rules=12 files=214628
Internal requirements count=1 size=108

then `sudo codesign -f -s XcodeSigner /Applications/Xcode.app`

/Applications/Xcode.app: replacing existing signature

After signing, `codesign -dv  /Applications/Xcode.app` outputs:

Executable=/Applications/Xcode.app/Contents/MacOS/Xcode
Identifier=com.apple.dt.Xcode
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20100 size=259 flags=0x0(none) hashes=3+3 location=embedded
Signature size=1733
Signed Time=21 Sep 2016, 18:37:25
Info.plist entries=36
TeamIdentifier=not set
Sealed Resources version=2 rules=13 files=214628
Internal requirements count=1 size=96

Git clone Xvim

`xcode-select -p`:
/Applications/Xcode.app/Contents/Developer

`make`: Xvim hasn’t confirmed ….
[y]

Target Xcode : /Applications/Xcode.app/Contents/Developer

With your Xcode version 8.0 it is required to remove code signature …
[y]

Close Xcode and press enter.
make[1]: `unsign' is up to date.
cp: /Applications/Xcode.app/Contents/Developer/../MacOS/Xcode_orig: Permission denied
The original Xcode binary is backed up to /Applications/Xcode.app/Contents/Developer/../MacOS/Xcode_orig
reading infile: /Applications/Xcode.app/Contents/Developer/../MacOS/Xcode
    found LC_CODE_SIGNATURE
not a fat binary
/Applications/Xcode.app/Contents/Developer/../MacOS/Xcode: Permission denied
/bin/sh: line 1:   747 Abort trap: 6           Tools/unsign/unsign ${xcode_path}/../MacOS/Xcode ${xcode_path}/../MacOS/Xcode
make: *** [code_unsign] Error 134

**Comment by JugglerShu** [comment]
@plm75 Sorry, I wrongly commit my fix to develop branch. I merged it to master. Makefile has changed. So please use the latest master's Makefile.

**Comment by plm75** [comment]
@JugglerShu 

Using latest commit fixes the problem. Thanks @JugglerShu
