### ISSUE TITLE
dd on first line of editor doesn't work.

### ISSUE THREAD

**Issue by AnthonyEgerton** [XVimProject/XVim#999]
## Steps to reproduce
1. Move to first line of a file in the editor
2. Press 'dd' to delete line
## Expected result

Line is deleted
## Actual result

Nothing happens

```
-------- Debug Info -------
XVim revision : 3eb09a6ffa68b4bc23b6d0703caea9e6152cd125
OS Version : Version 10.11.6 (Build 15G1004)
Xcode Version : 8.0

--- .xvmrc ---
N/A
--------------
```
##

**Comment by FredericRuaudel** [comment]
I confirmed this bug, but it happens only if the first line is empty or the cursor is in the first column of the line. 

This is a duplicate of #1004

**Comment by AnthonyEgerton** [comment]
Duplicate of https://github.com/XVimProject/XVim/issues/1004
